### ISSUE TITLE
Explore NPM npm/v1/user API

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/npm-registry-sdk#112]
Could be useful to explore the user API and found a way to fetch data for given user (if required)

See (old) doc: https://github.com/npm/registry/blob/master/docs/user/profile.md

**Comment by fraxken** [comment]
@kishore881 Yes the usecase is to use that to fetch more data about maintainers

The last endpoint seems quite cool, not fully related to the registry API but I guess we can implement it here.

**Comment by kishore881** [comment]
ohh in that case the users api in docs would not be useful at all since it returns the the caller's own profile details only but not for any given username. 
I will try to use 'https://www.npmjs.com/~{username}' and extract as much info as possible to build the same [User object](https://github.com/npm/registry/blob/master/docs/user/profile.md#profile) from registry docs.

**Comment by fraxken** [comment]
Hmm still a lot of useful informations (I checked with my acccount)

```
curl --request GET \
  --url 'https://www.npmjs.com/~fraxken' \
  --header 'x-spiferack: 1'
```

- Verified twitter & github accounts
- Links to some avatars (could solve our big struggle with avatar.io)
- Packages count and the full list (paginated)

And I guess we will never have tfa or email validation for obvious security reasons

**Comment by kishore881** [comment]
ohh, didn't notice the avatars already being shown.. unavata.io has rate-limit 300req/min..? is it not enough..? it also provides a json response with the url to image with ttl 1yr. would that be any useful 
```json
{"url":"https://images.weserv.nl/?url=https%3A%2F%2Favatars.githubusercontent.com%2Fu%2F2096101%3Fs%3D400%26v%3D4&default=https%3A%2F%2Favatars.githubusercontent.com%2Fu%2F2096101%3Fs%3D400%26v%3D4&l=9&af=&il=&n=-1&w=400&ttl=365d"}
```

**Comment by kishore881** [comment]
will a new version of this package be published..? to refer for imageElem in the cli

**Comment by fraxken** [comment]
@kishore881 I will release soon (or maybe @PierreDemailly if he want to do it). I'm quite busy this week because of family meals :)
